---

- name: Dot initialization
  hosts: localhost
  become: no
  vars:
    - home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    - dot: "{{ home }}/.dot"
  tasks:
    - name: Update submodules
      shell:
        "git submodule update --init --recursive"
      args:
        chdir: "{{ dot }}"
      register: update_log

    - name: Debug submodule update
      debug: msg='{{update_log.stdout_lines}}'

- import_playbook: install-apt-packages.yaml
- import_playbook: vim-bare.yaml
- import_playbook: terminal.yaml
  #- import_playbook: rust-tools.yaml

