# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
---

- name: install xmonad build dependencies
  hosts: localhost
  become: yes
  tasks:
    - name: dependencies
      ansible.builtin.apt:
        pkg:
          - stow
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - libxrandr-dev
          - libxss-dev
          - haskell-stack

    - name: update stack
      shell:
        "stack upgrade --force-download"

- name: copy configuration files
  hosts: localhost
  become: no
  vars:
    - home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    - dot: "{{ home }}/.dot"
  tasks:
    - name: deploy
      shell:
        "mkdir -p {{ home }}/.config/xmonad && stow -t {{ home }}/.config/xmonad xmonad"
      args:
        chdir: "{{ dot }}"

- name: compile xmonad
  hosts: localhost
  become: no
  vars:
    - home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    - src: "{{ home }}/.config/xmonad"
  tags:
    - compile
  tasks:
    - name: compile
      shell:
        "stack init --force && stack install"
      args:
        chdir: "{{ src }}"

    - name: add path to bashrc
      ansible.builtin.lineinfile:
        path: "{{ home }}/.bashrc"
        line: 'export PATH="$PATH/.local/bin"'
        state: present

