---

- name: install xmonad build dependencies
  hosts: localhost
  become: yes
  tasks:
    - name: dependencies
      ansible.builtin.apt:
        pkg:
          - stow
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - libxrandr-dev
          - libxss-dev
      register: build_dep_log

    - name: debug
      debug: msg='{{build_dep_log}}'

- name: copy configuration files
  hosts: localhost
  become: no
  vars:
    - home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    - dot: "{{ home }}/.dot"
  tasks:
    - name: deploy
      shell:
        "mkdir -p {{ home }}/.config/xmonad && stow --dotfiles dot -t {{ home }}/.config/xmonad -d xmonad"
      args:
        chdir: "{{ dot }}"
      register: deploy_log

    - name: debug
      debug: msg='{{deploy_log}}'
