# vim: set ts=2 sw=2 et smartindent :
name: Markdown

on: push

jobs:
  check-markdown:
    name: Check markdown to be nice
    runs-on: ubuntu-latest
    steps:
      - name: Markdown Linter
        uses: bewuethr/mdl-action@v1.1.2

